// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: service.proto

package gotemplate

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *User                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

// Facebase messages
type RegisterByTelegramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitDataRaw   string                 `protobuf:"bytes,1,opt,name=init_data_raw,json=initDataRaw,proto3" json:"init_data_raw,omitempty"`
	StartParam    string                 `protobuf:"bytes,2,opt,name=start_param,json=startParam,proto3" json:"start_param,omitempty"` // referrer telegram_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByTelegramRequest) Reset() {
	*x = RegisterByTelegramRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByTelegramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByTelegramRequest) ProtoMessage() {}

func (x *RegisterByTelegramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByTelegramRequest.ProtoReflect.Descriptor instead.
func (*RegisterByTelegramRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterByTelegramRequest) GetInitDataRaw() string {
	if x != nil {
		return x.InitDataRaw
	}
	return ""
}

func (x *RegisterByTelegramRequest) GetStartParam() string {
	if x != nil {
		return x.StartParam
	}
	return ""
}

type RegisterByTelegramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByTelegramResponse) Reset() {
	*x = RegisterByTelegramResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByTelegramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByTelegramResponse) ProtoMessage() {}

func (x *RegisterByTelegramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByTelegramResponse.ProtoReflect.Descriptor instead.
func (*RegisterByTelegramResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterByTelegramResponse) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type GetUserByTelegramIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTelegramIdRequest) Reset() {
	*x = GetUserByTelegramIdRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTelegramIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTelegramIdRequest) ProtoMessage() {}

func (x *GetUserByTelegramIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTelegramIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTelegramIdRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByTelegramIdRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x0eapi.gotemplate\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"O\n" +
	"\x0eGetUserRequest\x12=\n" +
	"\auser_id\x18\x01 \x01(\x03B$\x92A\x1e2\x1cThe UserId field description\xe0A\x02R\x06userId\";\n" +
	"\x0fGetUserResponse\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.api.gotemplate.UserR\x04data\"D\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\"e\n" +
	"\x19RegisterByTelegramRequest\x12'\n" +
	"\rinit_data_raw\x18\x01 \x01(\tB\x03\xe0A\x02R\vinitDataRaw\x12\x1f\n" +
	"\vstart_param\x18\x02 \x01(\tR\n" +
	"startParam\";\n" +
	"\x1aRegisterByTelegramResponse\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\"B\n" +
	"\x1aGetUserByTelegramIdRequest\x12$\n" +
	"\vtelegram_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"telegramId2\xb1\x01\n" +
	"\x05Users\x12\xa7\x01\n" +
	"\aGetUser\x12\x1e.api.gotemplate.GetUserRequest\x1a\x1f.api.gotemplate.GetUserResponse\"[\x92AH\x12\aGetUser\x1a=Метод для получения пользователя\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/user2\x9c\x03\n" +
	"\bFacebase\x12\xc7\x01\n" +
	"\x12RegisterByTelegram\x12).api.gotemplate.RegisterByTelegramRequest\x1a*.api.gotemplate.RegisterByTelegramResponse\"Z\x92A@\x12\x12RegisterByTelegram\x1a*Register user by Telegram WebApp init data\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/register\x12\xc5\x01\n" +
	"\x13GetUserByTelegramId\x12*.api.gotemplate.GetUserByTelegramIdRequest\x1a\x1f.api.gotemplate.GetUserResponse\"a\x92A6\x12\x13GetUserByTelegramId\x1a\x1fGet user profile by telegram id\x82\xd3\xe4\x93\x02\"\x12 /v1/users/telegram/{telegram_id}BL\x92A\x16\x12\x14\n" +
	"\vGO Template2\x051.0.0Z1gitlab16.skiftrade.kz/templates/go/api;gotemplateb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),             // 0: api.gotemplate.GetUserRequest
	(*GetUserResponse)(nil),            // 1: api.gotemplate.GetUserResponse
	(*User)(nil),                       // 2: api.gotemplate.User
	(*RegisterByTelegramRequest)(nil),  // 3: api.gotemplate.RegisterByTelegramRequest
	(*RegisterByTelegramResponse)(nil), // 4: api.gotemplate.RegisterByTelegramResponse
	(*GetUserByTelegramIdRequest)(nil), // 5: api.gotemplate.GetUserByTelegramIdRequest
}
var file_service_proto_depIdxs = []int32{
	2, // 0: api.gotemplate.GetUserResponse.data:type_name -> api.gotemplate.User
	0, // 1: api.gotemplate.Users.GetUser:input_type -> api.gotemplate.GetUserRequest
	3, // 2: api.gotemplate.Facebase.RegisterByTelegram:input_type -> api.gotemplate.RegisterByTelegramRequest
	5, // 3: api.gotemplate.Facebase.GetUserByTelegramId:input_type -> api.gotemplate.GetUserByTelegramIdRequest
	1, // 4: api.gotemplate.Users.GetUser:output_type -> api.gotemplate.GetUserResponse
	4, // 5: api.gotemplate.Facebase.RegisterByTelegram:output_type -> api.gotemplate.RegisterByTelegramResponse
	1, // 6: api.gotemplate.Facebase.GetUserByTelegramId:output_type -> api.gotemplate.GetUserResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
