// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: service.proto

package gotemplate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CyberMate_RegisterByTelegram_FullMethodName           = "/api.gotemplate.CyberMate/RegisterByTelegram"
	CyberMate_GetUserByTelegramId_FullMethodName          = "/api.gotemplate.CyberMate/GetUserByTelegramId"
	CyberMate_GetWalletByTelegramId_FullMethodName        = "/api.gotemplate.CyberMate/GetWalletByTelegramId"
	CyberMate_GetReferralsByTelegramId_FullMethodName     = "/api.gotemplate.CyberMate/GetReferralsByTelegramId"
	CyberMate_CreatePromptHistory_FullMethodName          = "/api.gotemplate.CyberMate/CreatePromptHistory"
	CyberMate_GetPromptHistoryByTelegramId_FullMethodName = "/api.gotemplate.CyberMate/GetPromptHistoryByTelegramId"
)

// CyberMateClient is the client API for CyberMate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CyberMate API
type CyberMateClient interface {
	// Registers a user based on Telegram init data; creates Profile and Wallet
	RegisterByTelegram(ctx context.Context, in *RegisterByTelegramRequest, opts ...grpc.CallOption) (*RegisterByTelegramResponse, error)
	// Returns user profile by telegram_id
	GetUserByTelegramId(ctx context.Context, in *GetUserByTelegramIdRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// Returns wallet summary and recent transactions.
	GetWalletByTelegramId(ctx context.Context, in *GetWalletByTelegramIdRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	// Returns the referral list for the current user.
	GetReferralsByTelegramId(ctx context.Context, in *GetReferralsByTelegramIdRequest, opts ...grpc.CallOption) (*GetReferralsResponse, error)
	// Saves a prompt to the current user's history.
	CreatePromptHistory(ctx context.Context, in *CreatePromptHistoryRequest, opts ...grpc.CallOption) (*CreatePromptHistoryResponse, error)
	// Returns saved prompt history for the current user.
	GetPromptHistoryByTelegramId(ctx context.Context, in *GetPromptHistoryByTelegramIdRequest, opts ...grpc.CallOption) (*GetPromptHistoryResponse, error)
}

type cyberMateClient struct {
	cc grpc.ClientConnInterface
}

func NewCyberMateClient(cc grpc.ClientConnInterface) CyberMateClient {
	return &cyberMateClient{cc}
}

func (c *cyberMateClient) RegisterByTelegram(ctx context.Context, in *RegisterByTelegramRequest, opts ...grpc.CallOption) (*RegisterByTelegramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterByTelegramResponse)
	err := c.cc.Invoke(ctx, CyberMate_RegisterByTelegram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberMateClient) GetUserByTelegramId(ctx context.Context, in *GetUserByTelegramIdRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, CyberMate_GetUserByTelegramId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberMateClient) GetWalletByTelegramId(ctx context.Context, in *GetWalletByTelegramIdRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, CyberMate_GetWalletByTelegramId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberMateClient) GetReferralsByTelegramId(ctx context.Context, in *GetReferralsByTelegramIdRequest, opts ...grpc.CallOption) (*GetReferralsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReferralsResponse)
	err := c.cc.Invoke(ctx, CyberMate_GetReferralsByTelegramId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberMateClient) CreatePromptHistory(ctx context.Context, in *CreatePromptHistoryRequest, opts ...grpc.CallOption) (*CreatePromptHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePromptHistoryResponse)
	err := c.cc.Invoke(ctx, CyberMate_CreatePromptHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberMateClient) GetPromptHistoryByTelegramId(ctx context.Context, in *GetPromptHistoryByTelegramIdRequest, opts ...grpc.CallOption) (*GetPromptHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPromptHistoryResponse)
	err := c.cc.Invoke(ctx, CyberMate_GetPromptHistoryByTelegramId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CyberMateServer is the server API for CyberMate service.
// All implementations must embed UnimplementedCyberMateServer
// for forward compatibility.
//
// CyberMate API
type CyberMateServer interface {
	// Registers a user based on Telegram init data; creates Profile and Wallet
	RegisterByTelegram(context.Context, *RegisterByTelegramRequest) (*RegisterByTelegramResponse, error)
	// Returns user profile by telegram_id
	GetUserByTelegramId(context.Context, *GetUserByTelegramIdRequest) (*GetUserResponse, error)
	// Returns wallet summary and recent transactions.
	GetWalletByTelegramId(context.Context, *GetWalletByTelegramIdRequest) (*GetWalletResponse, error)
	// Returns the referral list for the current user.
	GetReferralsByTelegramId(context.Context, *GetReferralsByTelegramIdRequest) (*GetReferralsResponse, error)
	// Saves a prompt to the current user's history.
	CreatePromptHistory(context.Context, *CreatePromptHistoryRequest) (*CreatePromptHistoryResponse, error)
	// Returns saved prompt history for the current user.
	GetPromptHistoryByTelegramId(context.Context, *GetPromptHistoryByTelegramIdRequest) (*GetPromptHistoryResponse, error)
	mustEmbedUnimplementedCyberMateServer()
}

// UnimplementedCyberMateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCyberMateServer struct{}

func (UnimplementedCyberMateServer) RegisterByTelegram(context.Context, *RegisterByTelegramRequest) (*RegisterByTelegramResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterByTelegram not implemented")
}
func (UnimplementedCyberMateServer) GetUserByTelegramId(context.Context, *GetUserByTelegramIdRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByTelegramId not implemented")
}
func (UnimplementedCyberMateServer) GetWalletByTelegramId(context.Context, *GetWalletByTelegramIdRequest) (*GetWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletByTelegramId not implemented")
}
func (UnimplementedCyberMateServer) GetReferralsByTelegramId(context.Context, *GetReferralsByTelegramIdRequest) (*GetReferralsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReferralsByTelegramId not implemented")
}
func (UnimplementedCyberMateServer) CreatePromptHistory(context.Context, *CreatePromptHistoryRequest) (*CreatePromptHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePromptHistory not implemented")
}
func (UnimplementedCyberMateServer) GetPromptHistoryByTelegramId(context.Context, *GetPromptHistoryByTelegramIdRequest) (*GetPromptHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPromptHistoryByTelegramId not implemented")
}
func (UnimplementedCyberMateServer) mustEmbedUnimplementedCyberMateServer() {}
func (UnimplementedCyberMateServer) testEmbeddedByValue()                   {}

// UnsafeCyberMateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CyberMateServer will
// result in compilation errors.
type UnsafeCyberMateServer interface {
	mustEmbedUnimplementedCyberMateServer()
}

func RegisterCyberMateServer(s grpc.ServiceRegistrar, srv CyberMateServer) {
	// If the following call panics, it indicates UnimplementedCyberMateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CyberMate_ServiceDesc, srv)
}

func _CyberMate_RegisterByTelegram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterByTelegramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberMateServer).RegisterByTelegram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberMate_RegisterByTelegram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberMateServer).RegisterByTelegram(ctx, req.(*RegisterByTelegramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberMate_GetUserByTelegramId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByTelegramIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberMateServer).GetUserByTelegramId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberMate_GetUserByTelegramId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberMateServer).GetUserByTelegramId(ctx, req.(*GetUserByTelegramIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberMate_GetWalletByTelegramId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletByTelegramIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberMateServer).GetWalletByTelegramId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberMate_GetWalletByTelegramId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberMateServer).GetWalletByTelegramId(ctx, req.(*GetWalletByTelegramIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberMate_GetReferralsByTelegramId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReferralsByTelegramIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberMateServer).GetReferralsByTelegramId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberMate_GetReferralsByTelegramId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberMateServer).GetReferralsByTelegramId(ctx, req.(*GetReferralsByTelegramIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberMate_CreatePromptHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromptHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberMateServer).CreatePromptHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberMate_CreatePromptHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberMateServer).CreatePromptHistory(ctx, req.(*CreatePromptHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberMate_GetPromptHistoryByTelegramId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromptHistoryByTelegramIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberMateServer).GetPromptHistoryByTelegramId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberMate_GetPromptHistoryByTelegramId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberMateServer).GetPromptHistoryByTelegramId(ctx, req.(*GetPromptHistoryByTelegramIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CyberMate_ServiceDesc is the grpc.ServiceDesc for CyberMate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CyberMate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.gotemplate.CyberMate",
	HandlerType: (*CyberMateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterByTelegram",
			Handler:    _CyberMate_RegisterByTelegram_Handler,
		},
		{
			MethodName: "GetUserByTelegramId",
			Handler:    _CyberMate_GetUserByTelegramId_Handler,
		},
		{
			MethodName: "GetWalletByTelegramId",
			Handler:    _CyberMate_GetWalletByTelegramId_Handler,
		},
		{
			MethodName: "GetReferralsByTelegramId",
			Handler:    _CyberMate_GetReferralsByTelegramId_Handler,
		},
		{
			MethodName: "CreatePromptHistory",
			Handler:    _CyberMate_CreatePromptHistory_Handler,
		},
		{
			MethodName: "GetPromptHistoryByTelegramId",
			Handler:    _CyberMate_GetPromptHistoryByTelegramId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
